/**
 * @fileoverview ID generation utilities for MHWS Set Builder.
 *
 * Provides functions for generating and validating unique IDs.
 * Strategy: Official IDs contain uppercase (e.g., HunterSkill_XXX, ARMOR_ID_XXX).
 *           Custom IDs are strictly lowercase with hyphens (e.g., skill-XXX, armor-XXX).
 */

import hash from "string-hash";

// MARK: Detection Helpers

/**
 * Checks if an ID is an official ID.
 * Official IDs start with uppercase or follow mixed-case conventions (e.g. HunterSkill_001, Bow_001).
 * @param id - The ID to check.
 * @returns True if it is an official ID.
 */
export function isOfficialId(id: string): boolean {
  if (!id || typeof id !== "string") return false;

  return (
    id === "NONE" ||
    id.startsWith("HunterSkill_") ||
    id.startsWith("ARMOR_ID_") ||
    id.startsWith("ACC_ID_") ||
    id.startsWith("CHARM_ID_") ||
    /^[A-Z][a-zA-Z]*_\d+$/.test(id) // Mixed case official weapon IDs
  );
}

/**
 * Checks if an ID is an official charm ID.
 * Official charm IDs start with "CHARM", e.g., "CHARM_ID_0008".
 * @param id - The ID to check.
 * @returns True if it is an official charm ID.
 */
export function isOfficialCharmId(id: string): boolean {
  return isOfficialId(id) && id.startsWith("CHARM");
}

/**
 * Checks if an ID is a custom ID (generated by this utility).
 * Custom IDs are strictly lowercase with specific prefixes.
 * @param id - The ID to check.
 * @returns True if it is a custom ID.
 */
export function isCustomId(id: string): boolean {
  if (!id || typeof id !== "string") return false;

  const validPrefixes = ["skill", "charm", "accessory", "armor", "weapon"];
  return validPrefixes.some((prefix) => id.startsWith(`${prefix}-`));
}

// MARK: Generators

/**
 * Generates a deterministic ID for a skill name.
 * Ensures that the same name always produces the same ID.
 * @param name - The name of the skill.
 * @returns A skill ID string (lowercase).
 */
export function generateSkillId(name: string): string {
  const uniqueHash = hash(name.trim());
  return `skill-${uniqueHash}`;
}

/**
 * Generates a new, non-deterministic charm ID.
 * @returns A charm ID string (e.g., "charm-1634567890123-abcd").
 */
export function generateCharmId(): string {
  return generateIdWithPrefix("charm");
}

/**
 * Generates a new, non-deterministic accessory ID.
 * @returns An accessory ID string (e.g., "accessory-1634567890123-abcd").
 */
export function generateAccessoryId(): string {
  return generateIdWithPrefix("accessory");
}

/**
 * Generates a new, non-deterministic armor ID.
 * @returns An armor ID string (e.g., "armor-1634567890123-abcd").
 */
export function generateArmorId(): string {
  return generateIdWithPrefix("armor");
}

/**
 * Generates a new, non-deterministic weapon ID.
 * @returns A weapon ID string (e.g., "weapon-1634567890123-abcd").
 */
export function generateWeaponId(): string {
  return generateIdWithPrefix("weapon");
}

/**
 * Helper function to generate an ID with a specific prefix.
 * @param prefix - The prefix to use.
 * @returns A formatted ID string.
 */
function generateIdWithPrefix(prefix: string): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 6); // 4-char random string
  return `${prefix}-${timestamp}-${random}`;
}

// MARK: Validation

/**
 * Validates if an ID has a correct format.
 * Checks against formats generated by `generateSkillId` or item ID generators.
 * @param id - The ID to validate.
 * @returns True if the format is correct.
 */
export function validateIdFormat(id: string): boolean {
  if (!id || typeof id !== "string") {
    return false;
  }

  // 1. Check if it's a known official format
  if (isOfficialId(id)) {
    return true;
  }

  // 2. Check for custom ID formats
  // Special case for deterministic skill IDs
  if (id.startsWith("skill-")) {
    const hashPart = id.substring(6);
    return /^\d+$/.test(hashPart);
  }

  // Generic custom ID format: {prefix}-{timestamp}-{4-char-random}
  const prefix = ["charm", "accessory", "armor", "weapon"].find((p) =>
    id.startsWith(`${p}-`),
  );

  if (prefix) {
    const parts = id.split("-");
    if (parts.length !== 3) return false;

    const [, timestamp, random] = parts;
    return /^\d{13}$/.test(timestamp) && /^[0-9a-z]{4}$/.test(random);
  }

  return false;
}
