/**
 * @fileoverview ID generation utilities for MHWS Set Builder.
 *
 * Provides functions for generating and validating unique IDs.
 */

import hash from "string-hash";

/**
 * Generates a deterministic ID for a skill name.
 * Ensures that the same name always produces the same ID.
 * @param name - The name of the skill.
 * @returns A skill ID string.
 */
export function generateSkillId(name: string): string {
  const uniqueHash = hash(name);
  return `skill-${uniqueHash}`;
}

/**
 * Checks if an ID is an official charm ID.
 * Official charm IDs start with "CHARM", e.g., "CHARM_ID_0008".
 * @param id - The ID to check.
 * @returns True if it is an official charm ID.
 */
export function isOfficialCharmId(id: string): boolean {
  return typeof id === "string" && id.startsWith("CHARM");
}

/**
 * Generates a new, non-deterministic charm ID.
 * Uses a timestamp and a short random string.
 * @returns A charm ID string (e.g., "charm-1634567890123-abcd").
 */
export function generateCharmId(): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 6); // 4-char random string
  return `charm-${timestamp}-${random}`;
}

/**
 * Validates if an ID has a correct format.
 * Checks against formats generated by `generateSkillId` or `generateCharmId`.
 * @param id - The ID to validate.
 * @returns True if the format is correct.
 */
export function validateIdFormat(id: string): boolean {
  if (!id || typeof id !== "string") {
    return false;
  }

  // Check for official skill ID formats like HunterSkill_XXX or NONE.
  if (
    id.startsWith("HunterSkill_") ||
    id === "NONE" ||
    /^[A-Z][a-zA-Z]*_\d+$/.test(id)
  ) {
    return true;
  }

  // Check for custom skill ID format: skill-{number}
  if (id.startsWith("skill-")) {
    const hashPart = id.substring(6); // Remove 'skill-'
    return /^\d+$/.test(hashPart);
  }

  // Check for charm ID format: charm-{timestamp}-{4-char-random}
  if (id.startsWith("charm-")) {
    const parts = id.split("-");
    if (parts.length !== 3) {
      return false;
    }

    const [, timestamp, random] = parts;

    // Validate timestamp: should be a 13-digit number (milliseconds).
    if (!/^\d{13}$/.test(timestamp)) {
      return false;
    }

    // Validate random string: should be 4 alphanumeric characters.
    if (!/^[0-9a-z]{4}$/.test(random)) {
      return false;
    }

    return true;
  }

  return false;
}
